from app.models.control import Control, FrameworkDefinition

FRAMEWORK = FrameworkDefinition(
    id="cis_csc",
    name="CIS Critical Security Controls",
    version="v8",
    family_weights={
        "Basic Controls": 1.5,
        "Foundational Controls": 1.3,
        "Organizational Controls": 1.1,
    },
    controls=[
        # Basic Controls (CIS Controls 1-6)
        Control("CIS-1", "Inventory and Control of Enterprise Assets",
                "Actively manage (inventory, track, and correct) all enterprise assets connected to the infrastructure physically, virtually, remotely, and those within cloud environments, to accurately know the totality of assets that need to be monitored and protected.",
                "Basic Controls", 1.5),
        Control("CIS-2", "Inventory and Control of Software Assets",
                "Actively manage all software on the network so that only authorized software is installed and can execute, and that unauthorized and unmanaged software is found and prevented from installation or execution.",
                "Basic Controls", 1.4),
        Control("CIS-3", "Data Protection",
                "Develop processes and technical controls to identify, classify, securely handle, retain, and dispose of data. Implement data loss prevention and encryption controls.",
                "Basic Controls", 1.5),
        Control("CIS-4", "Secure Configuration of Enterprise Assets and Software",
                "Establish and maintain the secure configuration of enterprise assets and software to prevent exploitation of vulnerabilities. Use hardening guides and configuration management processes.",
                "Basic Controls", 1.4),
        Control("CIS-5", "Account Management",
                "Use processes and tools to assign and manage authorization to credentials for user accounts, including administrator accounts, as well as service accounts, to enterprise assets and software.",
                "Basic Controls", 1.5),
        Control("CIS-6", "Access Control Management",
                "Use processes and tools to create, assign, manage, and revoke access credentials and privileges for user, administrator, and service accounts for enterprise assets and software.",
                "Basic Controls", 1.5),

        # Foundational Controls (CIS Controls 7-16)
        Control("CIS-7", "Continuous Vulnerability Management",
                "Develop a plan to continuously assess and track vulnerabilities on all enterprise assets within the enterprise's infrastructure, to remediate and minimize the window of opportunity for attackers.",
                "Foundational Controls", 1.4),
        Control("CIS-8", "Audit Log Management",
                "Collect, alert, review, and retain audit logs of events that could help detect, understand, or recover from an attack. Establish and maintain an audit log management process.",
                "Foundational Controls", 1.3),
        Control("CIS-9", "Email and Web Browser Protections",
                "Improve protections and detections of threats from email and web vectors, as these are opportunities for attackers to manipulate human behavior through direct engagement.",
                "Foundational Controls", 1.2),
        Control("CIS-10", "Malware Defenses",
                "Prevent or control the installation, spread, and execution of malicious applications, code, or scripts on enterprise assets through automated tools and processes.",
                "Foundational Controls", 1.3),
        Control("CIS-11", "Data Recovery",
                "Establish and maintain data recovery practices sufficient to restore in-scope enterprise assets to a pre-incident and trusted state. Test backup and recovery procedures regularly.",
                "Foundational Controls", 1.3),
        Control("CIS-12", "Network Infrastructure Management",
                "Establish and maintain the secure configuration of network infrastructure assets, including documentation and management of network diagrams, segmentation, and secure protocols.",
                "Foundational Controls", 1.3),
        Control("CIS-13", "Network Monitoring and Defense",
                "Operate processes and tooling to establish and maintain comprehensive network monitoring and defense against security threats across the enterprise's network infrastructure.",
                "Foundational Controls", 1.4),
        Control("CIS-14", "Security Awareness and Skills Training",
                "Establish and maintain a security awareness program to influence behavior among the workforce to be security conscious and properly skilled to reduce cybersecurity risks.",
                "Foundational Controls", 1.1),
        Control("CIS-15", "Service Provider Management",
                "Develop a process to evaluate service providers who hold sensitive data, or are responsible for an enterprise's critical IT platforms or processes, to ensure these providers are protecting those platforms and data appropriately.",
                "Foundational Controls", 1.0),
        Control("CIS-16", "Application Software Security",
                "Manage the security life cycle of in-house developed, hosted, or acquired software to prevent, detect, and remediate security weaknesses before they can impact the enterprise.",
                "Foundational Controls", 1.2),

        # Organizational Controls (CIS Controls 17-18)
        Control("CIS-17", "Incident Response Management",
                "Establish a program to develop and maintain an incident response capability to prepare, detect, contain, and eradicate attacks.",
                "Organizational Controls", 1.2),
        Control("CIS-18", "Penetration Testing",
                "Test the effectiveness and resiliency of enterprise assets through identifying and exploiting weaknesses in controls via simulated attack scenarios.",
                "Organizational Controls", 1.1),
    ],
)
