from app.models.control import Control, FrameworkDefinition

FRAMEWORK = FrameworkDefinition(
    id="hipaa",
    name="HIPAA Security Rule",
    version="2013",
    family_weights={
        "Administrative Safeguards": 1.4,
        "Physical Safeguards": 1.2,
        "Technical Safeguards": 1.5,
        "Organizational Requirements": 1.1,
        "Policies and Procedures": 1.2,
    },
    controls=[
        # Administrative Safeguards
        Control("164.308(a)(1)", "Security Management Process",
                "Implement policies and procedures to prevent, detect, contain, and correct security violations. Conduct an accurate and thorough risk analysis; implement security measures sufficient to reduce risks and vulnerabilities to ePHI.",
                "Administrative Safeguards", 1.5),
        Control("164.308(a)(2)", "Assigned Security Responsibility",
                "Identify the security official who is responsible for the development and implementation of the policies and procedures required for the entity.",
                "Administrative Safeguards", 1.2),
        Control("164.308(a)(3)", "Workforce Security",
                "Implement policies and procedures to ensure that all members of its workforce have appropriate access to electronic protected health information and to prevent those workforce members who do not have access from obtaining access.",
                "Administrative Safeguards", 1.3),
        Control("164.308(a)(4)", "Information Access Management",
                "Implement policies and procedures for authorizing access to electronic protected health information that are consistent with the applicable requirements of this subpart.",
                "Administrative Safeguards", 1.4),
        Control("164.308(a)(5)", "Security Awareness and Training",
                "Implement a security awareness and training program for all members of its workforce including management. Include protection from malicious software, log-in monitoring, and password management.",
                "Administrative Safeguards", 1.2),
        Control("164.308(a)(6)", "Security Incident Procedures",
                "Implement policies and procedures to address security incidents. Implement procedures to identify and respond to suspected or known security incidents and mitigate harmful effects.",
                "Administrative Safeguards", 1.3),
        Control("164.308(a)(7)", "Contingency Plan",
                "Establish and implement policies and procedures for responding to an emergency or other occurrence that damages systems containing ePHI. Include data backup plan, disaster recovery, emergency mode operations, testing, and applications criticality analysis.",
                "Administrative Safeguards", 1.3),
        Control("164.308(a)(8)", "Evaluation",
                "Perform a periodic technical and non-technical evaluation that establishes the extent to which an entity's security policies and procedures meet the requirements of the Security Rule.",
                "Administrative Safeguards", 1.1),

        # Physical Safeguards
        Control("164.310(a)(1)", "Facility Access Controls",
                "Implement policies and procedures to limit physical access to its electronic information systems and the facility or facilities in which they are housed, while ensuring that properly authorized access is allowed.",
                "Physical Safeguards", 1.2),
        Control("164.310(b)", "Workstation Use",
                "Implement policies and procedures that specify the proper functions to be performed, the manner in which those functions are to be performed, and the physical attributes of the surroundings of a specific workstation.",
                "Physical Safeguards", 1.1),
        Control("164.310(c)", "Workstation Security",
                "Implement physical safeguards for all workstations that access electronic protected health information, to restrict access to authorized users.",
                "Physical Safeguards", 1.1),
        Control("164.310(d)(1)", "Device and Media Controls",
                "Implement policies and procedures that govern the receipt and removal of hardware and electronic media that contain electronic protected health information into and out of a facility.",
                "Physical Safeguards", 1.2),

        # Technical Safeguards
        Control("164.312(a)(1)", "Access Control",
                "Implement technical policies and procedures for electronic information systems that maintain electronic protected health information to allow access only to those persons or software programs that have been granted access rights.",
                "Technical Safeguards", 1.5),
        Control("164.312(b)", "Audit Controls",
                "Implement hardware, software, and/or procedural mechanisms that record and examine activity in information systems that contain or use electronic protected health information.",
                "Technical Safeguards", 1.4),
        Control("164.312(c)(1)", "Integrity",
                "Implement policies and procedures to protect electronic protected health information from improper alteration or destruction. Implement electronic mechanisms to corroborate that ePHI has not been altered or destroyed.",
                "Technical Safeguards", 1.4),
        Control("164.312(d)", "Person or Entity Authentication",
                "Implement procedures to verify that a person or entity seeking access to electronic protected health information is the one claimed. Implement multi-factor authentication where feasible.",
                "Technical Safeguards", 1.4),
        Control("164.312(e)(1)", "Transmission Security",
                "Implement technical security measures to guard against unauthorized access to electronic protected health information that is being transmitted over an electronic communications network.",
                "Technical Safeguards", 1.5),

        # Organizational Requirements
        Control("164.314(a)(1)", "Business Associate Contracts",
                "A covered entity must enter into a contract or other arrangement with business associates that will provide satisfactory assurances that the business associate will appropriately safeguard ePHI.",
                "Organizational Requirements", 1.1),

        # Policies and Procedures
        Control("164.316(a)", "Policies and Procedures",
                "Implement reasonable and appropriate policies and procedures to comply with the standards and implementation specifications. Maintain written security policies and procedures.",
                "Policies and Procedures", 1.2),
        Control("164.316(b)(1)", "Documentation",
                "Maintain the policies and procedures implemented to comply with this subpart in written form. Retain documentation for 6 years from the date of its creation or the date when it last was in effect.",
                "Policies and Procedures", 1.1),
    ],
)
