from app.models.control import Control, FrameworkDefinition

FRAMEWORK = FrameworkDefinition(
    id="nist_csf",
    name="NIST Cybersecurity Framework",
    version="1.1",
    family_weights={
        "Identify": 1.2,
        "Protect": 1.5,
        "Detect": 1.3,
        "Respond": 1.2,
        "Recover": 1.0,
    },
    controls=[
        # IDENTIFY
        Control("ID.AM-1", "Asset Management: Physical Device Inventory",
                "Physical devices and systems within the organization are inventoried, including hardware, software, and firmware components.",
                "Identify", 1.0),
        Control("ID.AM-2", "Asset Management: Software Platform Inventory",
                "Software platforms and applications within the organization are inventoried and managed throughout their lifecycle.",
                "Identify", 1.0),
        Control("ID.BE-1", "Business Environment: Role in Supply Chain",
                "The organization's role in the supply chain is identified and communicated, including dependencies and critical functions.",
                "Identify", 1.0),
        Control("ID.GV-1", "Governance: Cybersecurity Policy",
                "Organizational cybersecurity policy is established, documented, and communicated to all personnel with cybersecurity responsibilities.",
                "Identify", 1.2),
        Control("ID.RA-1", "Risk Assessment: Asset Vulnerabilities",
                "Asset vulnerabilities are identified and documented through regular vulnerability assessments and penetration testing.",
                "Identify", 1.2),
        Control("ID.RA-3", "Risk Assessment: Threat Information",
                "Threats, both internal and external, are identified and documented; threat intelligence is received from information sharing forums.",
                "Identify", 1.0),
        Control("ID.SC-1", "Supply Chain Risk Management: Policy",
                "Cyber supply chain risk management processes are identified, established, assessed, managed, and agreed to by organizational stakeholders.",
                "Identify", 1.0),

        # PROTECT
        Control("PR.AC-1", "Identity Management and Access Control: Identities",
                "Identities and credentials are issued, managed, verified, revoked, and audited for authorized devices, users, and processes.",
                "Protect", 1.5),
        Control("PR.AC-3", "Identity Management and Access Control: Remote Access",
                "Remote access is managed with multi-factor authentication, encryption, and least-privilege principles enforced for remote sessions.",
                "Protect", 1.3),
        Control("PR.DS-1", "Data Security: Data-at-Rest Protection",
                "Data-at-rest is protected through encryption, access controls, and data classification policies aligned with organizational risk.",
                "Protect", 1.5),
        Control("PR.DS-2", "Data Security: Data-in-Transit Protection",
                "Data-in-transit is protected using strong encryption protocols and secure communication channels.",
                "Protect", 1.5),
        Control("PR.IP-1", "Information Protection: Baseline Configuration",
                "A baseline configuration of information technology and industrial control systems is created and maintained incorporating security principles.",
                "Protect", 1.2),
        Control("PR.IP-12", "Information Protection: Vulnerability Management",
                "A vulnerability management plan is developed and implemented to identify, prioritize, and remediate vulnerabilities in a timely manner.",
                "Protect", 1.3),
        Control("PR.AT-1", "Awareness and Training: User Training",
                "All users are informed and trained on cybersecurity awareness, including phishing, social engineering, and acceptable use policies.",
                "Protect", 1.0),
        Control("PR.PT-1", "Protective Technology: Audit Log Management",
                "Audit and log records are determined, documented, implemented, and reviewed in accordance with policy to enable monitoring and incident investigation.",
                "Protect", 1.2),

        # DETECT
        Control("DE.AE-1", "Anomalies and Events: Baseline Network Operations",
                "A baseline of network operations and expected data flows for users and systems is established and managed to identify anomalies.",
                "Detect", 1.2),
        Control("DE.CM-1", "Security Continuous Monitoring: Network Monitoring",
                "The network is monitored to detect potential cybersecurity events through continuous monitoring tools and processes.",
                "Detect", 1.5),
        Control("DE.CM-7", "Security Continuous Monitoring: Unauthorized Personnel",
                "Monitoring for unauthorized personnel, connections, devices, and software is performed continuously.",
                "Detect", 1.2),
        Control("DE.DP-1", "Detection Processes: Roles and Responsibilities",
                "Roles and responsibilities for detection are well defined to ensure accountability for detection activities and processes.",
                "Detect", 1.0),

        # RESPOND
        Control("RS.RP-1", "Response Planning: Response Plan",
                "Response plan is executed during or after an incident, including roles, responsibilities, and communication procedures.",
                "Respond", 1.5),
        Control("RS.CO-2", "Communications: Incident Reporting",
                "Incidents are reported consistent with established criteria, including internal escalation paths and external reporting requirements.",
                "Respond", 1.2),
        Control("RS.AN-1", "Analysis: Alerts Investigation",
                "Notifications from detection systems are investigated to understand attack targets, methods, and potential impacts.",
                "Respond", 1.2),
        Control("RS.MI-1", "Mitigation: Incidents Contained",
                "Incidents are contained to minimize impact, including isolation of affected systems and preservation of forensic evidence.",
                "Respond", 1.3),

        # RECOVER
        Control("RC.RP-1", "Recovery Planning: Recovery Plan",
                "Recovery plan is executed during or after a cybersecurity incident, with documented procedures for restoration of systems and data.",
                "Recover", 1.5),
        Control("RC.IM-1", "Improvements: Recovery Plans Incorporate Lessons Learned",
                "Recovery plans incorporate lessons learned from past incidents and exercises to improve future response and recovery capabilities.",
                "Recover", 1.0),
        Control("RC.CO-3", "Communications: Recovery Activities Communicated",
                "Recovery activities are communicated to internal and external stakeholders as well as executive and management teams.",
                "Recover", 1.0),
    ],
)
